"""empty message

Revision ID: 5961e0380f42
Revises: 2807edd385a2
Create Date: 2022-02-07 18:36:51.682291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5961e0380f42'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proponent', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=20), nullable=False),
    sa.Column('proposal_type', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('documents', sa.String(length=120), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('document_description', sa.String(length=1000), nullable=True),
    sa.Column('contact_by', sa.String(length=20), nullable=False),
    sa.Column('confirmation_by', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['proponent'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('address', sa.String(length=240), nullable=False))
    op.add_column('user', sa.Column('home_phone', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('mobile_phone', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('years_of_residence', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('zip_code', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'user', ['mobile_phone'])
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'zip_code')
    op.drop_column('user', 'years_of_residence')
    op.drop_column('user', 'user_id')
    op.drop_column('user', 'name')
    op.drop_column('user', 'mobile_phone')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'home_phone')
    op.drop_column('user', 'address')
    op.drop_table('proposal')
    # ### end Alembic commands ###
