"""empty message

Revision ID: 5fb13aa8cf07
Revises: 
Create Date: 2022-02-23 20:39:45.927644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb13aa8cf07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('lastname', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('home_phone', sa.String(length=20), nullable=True),
    sa.Column('mobile_phone', sa.String(length=20), nullable=False),
    sa.Column('address1', sa.String(length=240), nullable=True),
    sa.Column('address2', sa.String(length=240), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('years_of_residence', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile_phone')
    )
    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=20), nullable=False),
    sa.Column('proposal_type', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('documents', sa.String(length=120), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('document_description', sa.String(length=1000), nullable=True),
    sa.Column('contact_by', sa.String(length=20), nullable=False),
    sa.Column('confirmation_by', sa.String(length=20), nullable=False),
    sa.Column('proponent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proponent_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposal')
    op.drop_table('user')
    # ### end Alembic commands ###
