"""empty message

Revision ID: aecba60f7e92
Revises: 9500742fad76
Create Date: 2022-03-16 14:23:36.215404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aecba60f7e92'
down_revision = '9500742fad76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('start', sa.String(length=800), nullable=False))
    op.add_column('project', sa.Column('cost', sa.String(length=800), nullable=False))
    op.add_column('project', sa.Column('taxes', sa.String(length=800), nullable=False))
    op.add_column('project', sa.Column('developer', sa.String(length=800), nullable=False))
    op.add_column('project', sa.Column('jobs', sa.String(length=800), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'jobs')
    op.drop_column('project', 'developer')
    op.drop_column('project', 'taxes')
    op.drop_column('project', 'cost')
    op.drop_column('project', 'start')
    # ### end Alembic commands ###
